name: melihhakanpektas
description: "A personal website for Melih Hakan Pektas."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  material_design_icons_flutter: ^7.0.7296
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/background_images/
    - assets/pdfs/
